import uuid from 'uuid'

const items = [
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'course',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
    {
      id: uuid(),
      link: 'http://google.com',
      img: `https://source.unsplash.com/random/300x20${uuid()}`,
      imgSmall: `https://source.unsplash.com/random/100x50${uuid()}`,
      type: 'video',
      title: 'Introduction to Machine Learning Problem Framing',
      description: 'This one-hour course introduces the machine learning mindset and helps you identify appropriate situations for machine learning.',
    },
  ]

export default items